
import React, { useState, useEffect, useCallback } from 'react';
import { Member, Donation, AppState } from './types';
import { STORAGE_KEY, REGISTRATION_FEE, MUSLIM_MALE_REGISTRATION_FEE } from './constants';
import Header from './components/Header';
import Home from './components/Home';
import RegistrationForm from './components/RegistrationForm';
import Directory from './components/Directory';
import FundManagement from './components/FundManagement';
import MemberProfile from './components/MemberProfile';
import DikriYojnaForm from './components/DikriYojnaForm';
import Footer from './components/Footer';

const App: React.FC = () => {
  const [view, setView] = useState<'HOME' | 'REGISTER' | 'DIRECTORY' | 'FUND' | 'PROFILE' | 'DIKRI_YOJNA'>('HOME');
  const [selectedMemberId, setSelectedMemberId] = useState<string | null>(null);
  const [editingMember, setEditingMember] = useState<Member | null>(null);
  
  const [data, setData] = useState<AppState>(() => {
    const saved = localStorage.getItem(STORAGE_KEY);
    return saved ? JSON.parse(saved) : { members: [], donations: [] };
  });

  // Cross-tab synchronization
  useEffect(() => {
    const handleStorageChange = (e: StorageEvent) => {
      if (e.key === STORAGE_KEY && e.newValue) {
        setData(JSON.parse(e.newValue));
      }
    };
    window.addEventListener('storage', handleStorageChange);
    return () => window.removeEventListener('storage', handleStorageChange);
  }, []);

  const syncRecurringFunds = useCallback(() => {
    const now = new Date();
    let updatedMembers = [...data.members];
    let newDonations: Donation[] = [];
    let hasChanges = false;

    updatedMembers = updatedMembers.map(member => {
      if (!member.recurringConfig.enabled || member.recurringConfig.type === 'NONE') return member;

      const lastSync = member.lastAutoSyncDate ? new Date(member.lastAutoSyncDate) : new Date(member.registrationDate);
      const diffMs = now.getTime() - lastSync.getTime();
      
      let periods = 0;
      if (member.recurringConfig.type === 'DAILY') {
        periods = Math.floor(diffMs / (1000 * 60 * 60 * 24));
      } else if (member.recurringConfig.type === 'MONTHLY') {
        periods = Math.floor(diffMs / (1000 * 60 * 60 * 24 * 30));
      }

      if (periods > 0) {
        hasChanges = true;
        for (let i = 1; i <= periods; i++) {
          const donationDate = new Date(lastSync);
          if (member.recurringConfig.type === 'DAILY') {
            donationDate.setDate(donationDate.getDate() + i);
          } else {
            donationDate.setMonth(donationDate.getMonth() + i);
          }

          newDonations.push({
            id: `auto-${Math.random().toString(36).substr(2, 9)}`,
            memberId: member.id,
            memberName: member.fullName,
            amount: member.recurringConfig.amount,
            date: donationDate.toISOString(),
            category: 'PATHAN_FUND',
            subCategory: `ઓટો ${member.recurringConfig.type === 'DAILY' ? 'દૈનિક' : 'માસિક'} ફંડ`,
            isAutoGenerated: true,
            message: 'સિસ્ટમ દ્વારા ઓટોમેટિક એડ કરેલ',
            type: 'DEPOSIT'
          });
        }
        return { ...member, lastAutoSyncDate: now.toISOString() };
      }
      return member;
    });

    if (hasChanges) {
      setData(prev => ({
        members: updatedMembers,
        donations: [...prev.donations, ...newDonations]
      }));
    }
  }, [data.members]);

  useEffect(() => {
    syncRecurringFunds();
  }, []);

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  }, [data]);

  const addMember = (member: Member) => {
    let initialDonations: Donation[] = [];
    
    const fee = (member.gender === 'MALE' && member.community === 'MUSLIM') 
      ? MUSLIM_MALE_REGISTRATION_FEE 
      : REGISTRATION_FEE;

    initialDonations.push({
      id: `reg-fee-${Math.random().toString(36).substr(2, 9)}`,
      memberId: member.id,
      memberName: member.fullName,
      amount: fee,
      date: new Date().toISOString(),
      category: 'GENERAL',
      subCategory: 'રજિસ્ટ્રેશન ફી',
      message: 'નવા સભ્ય રજિસ્ટ્રેશન ફી',
      type: 'DEPOSIT'
    });

    if (member.recurringConfig.enabled && member.recurringConfig.type !== 'NONE') {
      initialDonations.push({
        id: `init-rec-${Math.random().toString(36).substr(2, 9)}`,
        memberId: member.id,
        memberName: member.fullName,
        amount: member.recurringConfig.amount,
        date: new Date().toISOString(),
        category: 'PATHAN_FUND',
        subCategory: `${member.recurringConfig.type === 'DAILY' ? 'પ્રથમ દૈનિક' : 'પ્રથમ માસિક'} ફંડ`,
        isAutoGenerated: false,
        message: 'રજિસ્ટ્રેશન સાથે પ્રથમ ફાળો',
        type: 'DEPOSIT'
      });
      member.lastAutoSyncDate = new Date().toISOString();
    }

    setData(prev => ({
      ...prev,
      members: [member, ...prev.members],
      donations: [...initialDonations, ...prev.donations]
    }));
    setView('DIRECTORY');
  };

  const updateMember = (updatedMember: Member) => {
    setData(prev => ({
      ...prev,
      members: prev.members.map(m => m.id === updatedMember.id ? updatedMember : m)
    }));
    setEditingMember(null);
    setSelectedMemberId(updatedMember.id);
    setView('PROFILE');
  };

  const addDonation = (donation: Donation) => {
    setData(prev => ({
      ...prev,
      donations: [donation, ...prev.donations]
    }));
  };

  const handleViewMember = (id: string) => {
    setSelectedMemberId(id);
    setView('PROFILE');
  };

  const handleEditMember = (member: Member) => {
    setEditingMember(member);
    setView('REGISTER');
  };

  return (
    <div className="min-h-screen flex flex-col bg-slate-50 text-slate-900">
      <Header currentView={view} setView={(v) => {
        setEditingMember(null);
        setView(v);
      }} />
      <main className="flex-grow container mx-auto px-4 py-8">
        {(() => {
          switch (view) {
            case 'HOME':
              return <Home onAction={(v) => setView(v)} membersCount={data.members.length} />;
            case 'REGISTER':
              return (
                <RegistrationForm 
                  onSubmit={editingMember ? updateMember : addMember} 
                  initialData={editingMember || undefined}
                  isEditing={!!editingMember}
                  onCancel={() => {
                    setEditingMember(null);
                    setView(selectedMemberId ? 'PROFILE' : 'DIRECTORY');
                  }}
                />
              );
            case 'DIRECTORY':
              return <Directory members={data.members} onViewMember={handleViewMember} />;
            case 'FUND':
              return <FundManagement members={data.members} donations={data.donations} onDonate={addDonation} onViewMember={handleViewMember} />;
            case 'PROFILE':
              const member = data.members.find(m => m.id === selectedMemberId);
              const memberDonations = data.donations.filter(d => d.memberId === selectedMemberId);
              return member ? (
                <MemberProfile 
                  member={member} 
                  donations={memberDonations} 
                  onEdit={() => handleEditMember(member)}
                  onBack={() => setView('DIRECTORY')}
                />
              ) : <Directory members={data.members} onViewMember={handleViewMember} />;
            case 'DIKRI_YOJNA':
              return (
                <DikriYojnaForm 
                  members={data.members} 
                  onClaim={(donation) => {
                    addDonation(donation);
                    setView('PROFILE');
                    setSelectedMemberId(donation.memberId);
                  }}
                  onCancel={() => setView('HOME')}
                />
              );
            default:
              return <Home onAction={(v) => setView(v)} membersCount={data.members.length} />;
          }
        })()}
      </main>
      <Footer />
    </div>
  );
};

export default App;
