
export type Community = 'PATEL' | 'MUSLIM';
export type SubCaste = 'LEUVA' | 'KADVA' | string;
export type OccupationType = 'JOB' | 'BUSINESS' | 'NONE' | 'GHARKAM' | 'RAKHEL' | 'NETA' | 'UMEDVAR';
export type MaritalStatus = 'MARRIED' | 'UNMARRIED';
export type NameSuffixPreference = 'FATHER' | 'HUSBAND' | 'NONE';
export type Gender = 'MALE' | 'FEMALE';

export type FundMainCategory = 'SNEHMILAN' | 'LAGAN' | 'WOMEN_ASSISTANCE' | 'PATHAN_FUND' | 'GENERAL' | 'WITHDRAWAL' | 'DIKRI_YOJNA';

export interface RecurringConfig {
  type: 'NONE' | 'DAILY' | 'MONTHLY';
  amount: number;
  enabled: boolean;
}

export interface RakhelDetails {
  ofWhoseName: string;
  years: number;
}

export interface Member {
  id: string;
  registrationNumber: string;
  fullName: string;
  gender: Gender;
  photo?: string;
  fatherName: string;
  husbandName?: string;
  maritalStatus: MaritalStatus;
  nameSuffixPreference: NameSuffixPreference;
  useHusbandSuffix: boolean;
  age: number; // For single
  wifeAge?: number; // For married
  husbandAge?: number; // For married
  city: string;
  community: Community;
  subCaste: SubCaste;
  womanCaste?: string;
  husbandCaste?: string;
  education?: string;
  wifeEducation?: string;
  occupationType: OccupationType;
  wifeOccupation?: OccupationType;
  occupationDetails: string;
  annualIncome: number;
  registrationFeePaid: boolean;
  registrationDate: string;
  recurringConfig: RecurringConfig;
  lastAutoSyncDate?: string;
  isRakhel: boolean;
  rakhelDetails?: RakhelDetails;
}

export interface Donation {
  id: string;
  memberId: string;
  memberName: string;
  amount: number;
  date: string;
  category: FundMainCategory;
  subCategory?: string;
  count?: number;
  message?: string;
  isAutoGenerated?: boolean;
  type: 'DEPOSIT' | 'WITHDRAWAL';
}

export interface AppState {
  members: Member[];
  donations: Donation[];
}
